# This rule is not used by the project hyperkube itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to hcp.gcp.hypershift.openshift.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hyperkube
    app.kubernetes.io/managed-by: kustomize
  name: managedhostedcluster-viewer-role
rules:
- apiGroups:
  - hcp.gcp.hypershift.openshift.com
  resources:
  - managedhostedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hcp.gcp.hypershift.openshift.com
  resources:
  - managedhostedclusters/status
  verbs:
  - get
