apiVersion: hcp.gcp.hypershift.openshift.com/v1alpha1
kind: HostedClusterTemplate
metadata:
  labels:
    app.kubernetes.io/name: gcp-hcp-backend
    app.kubernetes.io/managed-by: kustomize
  name: gcp-standard-4-16
spec:
  version: "4.16"
  template: |
    apiVersion: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    spec:
      release:
        image: "{{ .ReleaseImage }}"
      infraID: {{ .ClusterID }}
      platform:
        type: None
      etcd:
        managementType: Managed
        managed:
          storage:
            type: PersistentVolume
      services:
        - service: APIServer
          servicePublishingStrategy:
            type: LoadBalancer
        - service: OAuthServer
          servicePublishingStrategy:
            type: Route
        - service: Konnectivity
          servicePublishingStrategy:
            type: Route
        - service: Ignition
          servicePublishingStrategy:
            type: Route
      networking:
        clusterNetwork:
          - cidr: 10.132.0.0/14
        serviceNetwork:
          - cidr: 172.31.0.0/16
