apiVersion: hcp.gcp.hypershift.openshift.com/v1alpha1
kind: VersionStream
metadata:
  labels:
    app.kubernetes.io/name: hyperkube
    app.kubernetes.io/managed-by: kustomize
  name: stable
spec:
  targetVersion: "4.16"
  channelGroup: "stable"
  arch: "amd64"
